export const AUTO_LIST_REQUEST = 'AUTO_LIST_REQUEST';
export const AUTO_LIST_SUCCESS = 'AUTO_LIST_SUCCESS';
export const AUTO_LIST_FAIL = 'AUTO_LIST_FAIL';

export const AUTO_DETAILS_REQUEST = 'AUTO_DETAILS_REQUEST';
export const AUTO_DETAILS_SUCCESS = 'AUTO_DETAILS_SUCCESS';
export const AUTO_DETAILS_FAIL = 'AUTO_DETAILS_FAIL';

export const AUTO_CREATE_REQUEST = 'AUTO_CREATE_REQUEST';
export const AUTO_CREATE_SUCCESS = 'AUTO_CREATE_SUCCESS';
export const AUTO_CREATE_FAIL = 'AUTO_CREATE_FAIL';
export const AUTO_CREATE_RESET = 'AUTO_CREATE_RESET';

export const AUTO_UPDATE_REQUEST = 'AUTO_UPDATE_REQUEST';
export const AUTO_UPDATE_SUCCESS = 'AUTO_UPDATE_SUCCESS';
export const AUTO_UPDATE_FAIL = 'AUTO_UPDATE_FAIL';
export const AUTO_UPDATE_RESET = 'AUTO_UPDATE_RESET';

export const AUTO_DELETE_REQUEST = 'AUTO_DELETE_REQUEST';
export const AUTO_DELETE_SUCCESS = 'AUTO_DELETE_SUCCESS';
export const AUTO_DELETE_FAIL = 'AUTO_DELETE_FAIL';
export const AUTO_DELETE_RESET = 'AUTO_DELETE_RESET';

export const AUTO_OFFICE_LIST_REQUEST = 'AUTO_OFFICE_LIST_REQUEST';
export const AUTO_OFFICE_LIST_SUCCESS = 'AUTO_OFFICE_LIST_SUCCESS';
export const AUTO_OFFICE_LIST_FAIL = 'AUTO_OFFICE_LIST_FAIL';